export enum UserRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  BRANCH_ADMIN = "BRANCH_ADMIN",
  VIEWER = "VIEWER"
}

export enum SessionStatus {
  ACTIVE = "ACTIVE",
  TERMINATED = "TERMINATED",
  EXPIRED = "EXPIRED",
  BLOCKED = "BLOCKED"
}

export enum AuditActionType {
  LOGIN_ATTEMPT = "LOGIN_ATTEMPT",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",
  LOGOUT = "LOGOUT",
  SECURITY_POLICY_UPDATED = "SECURITY_POLICY_UPDATED",
  OTP_SENT = "OTP_SENT",
  DEVICE_APPROVED = "DEVICE_APPROVED",
  DEVICE_BLOCKED = "DEVICE_BLOCKED",
  USER_BLOCKED = "USER_BLOCKED",
  USER_RESTORED = "USER_RESTORED"
}

export enum SecurityEventType {
  LOGIN_FAILURE = "LOGIN_FAILURE",
  DISALLOWED_IP = "DISALLOWED_IP",
  OTP_FAILURE = "OTP_FAILURE",
  DEVICE_NOT_REGISTERED = "DEVICE_NOT_REGISTERED",
  CONCURRENT_SESSION_BLOCKED = "CONCURRENT_SESSION_BLOCKED",
  SESSION_TAKEOVER = "SESSION_TAKEOVER",
  BLOCKED_DEVICE_LOGIN = "BLOCKED_DEVICE_LOGIN"
}
